---
- project:
    templates:
      - stx-api-ref-jobs
      - publish-stx-docs
      - stx-release-notes-jobs
      - stx-bandit-jobs
    check:
      jobs:
        - metal-tox-linters
        - metal-tox-pep8
        - metal-tox-pylint
    gate:
      jobs:
        - metal-tox-linters
        - metal-tox-pep8
        - metal-tox-pylint
    post:
      jobs:
        - stx-metal-upload-git-mirror

- job:
    name: metal-tox-linters
    parent: tox
    description: Run linters for metal repo
    nodeset: debian-bullseye
    vars:
      tox_envlist: linters

- job:
    name: metal-tox-pep8
    parent: tox
    description: Run pep8 for metal repo
    nodeset: debian-bullseye
    vars:
      tox_envlist: pep8

- job:
    name: metal-tox-pylint
    parent: tox
    description: Run pylint for metal repo
    nodeset: debian-bullseye
    vars:
      tox_envlist: pylint

- job:
    name: flock-devstack-metal
    parent: flock-devstack-base-min
    required-projects:
      - openstack/barbican
      - openstack/python-barbicanclient
      - starlingx/fault
      - starlingx/integ
      - starlingx/nfv
      - starlingx/update
      - starlingx/utilities
    vars:
      tox_envlist: functional
      devstack_services:
        # StarlingX services
        fm-common: true
        # fm-api: true
        # mtce: true
        mtce-compute: true
        mtce-control: true
        mtce-storage: true
        inventory-api: true
        inventory-conductor: true
        inventory-agent: true
        inventory-client: true
        fsmon: true
        hbs: true
        hwmon: true
        mtcalarm: true
        mtclog: true
        pmon: true
        rmon: true
      devstack_plugins:
        barbican: https://opendev.org/openstack/barbican
        fault: https:://opendev.org/starlingx/fault
        integ: https://opendev.org/starlingx/integ
        metal: https:://opendev.org/starlingx/metal
        # nfv: https:://opendev.org/starlingx/nfv
        update: https:://opendev.org/starlingx/update

- job:
    name: stx-metal-upload-git-mirror
    parent: upload-git-mirror
    description: >
      Mirrors opendev.org/starlingx/metal to
      github.com/starlingx/metal
    vars:
      git_mirror_repository: starlingx/metal
    secrets:
      - name: git_mirror_credentials
        secret: stx-metal-github-secret3
        pass-to-parent: true

- secret:
    name: stx-metal-github-secret3
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      ssh_key: !encrypted/pkcs1-oaep
        - FJ0K0o1GowtuTQ9Rf1VAGx5yLM9k/z34cUEcK6wjSN4FLVO/Zcjyg2DD9nfG1b9leZP53
          DNL8zsUCyhUC50VvvEksbcAVGFYGygYTaLMEB5A3kXie3skEfvxePFNJKqxwpTPV0HnBq
          f3YjwHQeN4i8h5ZhamtROeFJ6AOwpCZjb1Y726EdwqPQ4wZ5PiVwiR9LMz8zobNTBU44H
          GaY5Ja0PK79NiU2eft9eynlEsd8Qu5wG6eIP7IfgBDY+FKiNxKswwSmDGDBQcGCiv/49v
          9gKyKdeQaJHkEVWqryxUnB1YOVQeO2GHUypHqQ2OwpYLKtX0V9YTI/cGYSFBMu2a3nlQv
          dTJ6pAVJnfGw2e76tOEj3dUkosDEN6O7D9kWtEcGhy30amOxDGu7pmMcOCloNK4ZDxjQA
          Os+Zf0t6dNMwzS1SGbPSvmAEdOvA6doYSATqvF+dWwd4jVM2nKDBhwbIzxkBrr3e3Tuex
          bn6Jt34tprhuivnihFTmUue5K/0J+XnVFM1udTAN6Ai8ulGd7XxBpE4fonJ7Xigo5owdn
          glUgHpWqhjgBEyI2ILJy5iHN8d16zWu3iK7+yMtLAgzqCkZwhyIxgs4xY0+Q13l8mJgHD
          JxFRiI57Wgxq1RqsWYq5uVNBMj3LXu9zOU7pS8W7JBzsahilOR0tH3wt+gaxwE=
        - v/HskJ9lFmZQFFy1rsUR9ndSHHn2i1jKJQmRgyg2jjXGgcvbH6KZHqTtHLe7SPGcMkQa6
          7PyIdUF/fpr7WbuOTQZk9VwExVfZDL45rg2dOrqLI8EhboLzl20NZCvGFQit5uebJ+T9n
          sDhviD54UPBe+KRCnT5lEDTxx5AlzC3hRs6buqAxYBkhaOpbAn/LyFsxSZdklEkXVm4XL
          OHhmvgZUSz6w5DqlGRjWjugZLNSfra8aUhCMurnO8jpqHUfhNML6ATsuNhNSvkliO0Ath
          t2DI0MqCsWfwfrrhSUUudZk9a5jcLtX2XEc9miwSMNwXcnlTz8G4I3JSLGKOwaDtEGbXd
          ha+l2MUXKXvIopMO6jOSAkHhGe0qKEWt4gr2X+NWzknhXUrC/lnV6aFVZnvsBjDdirrjH
          2No0mxdnpdqVLoRH950x5q9a9xhh6rW0KbKUfBQ3XG5SdwKbPURGSsR2QK1o3whM08S8C
          WBSV7CT0cMBY6wEdnB8+Kp23NW5x8/o+mpCFQ/dMGIsTngWHqYGtTJMPlnPGRRN+JleIa
          mIISsJU+hm584gfKDqup0fZiOjPM3Loa/EOR3GRNMAt4EG3RorNFi2glbD9SLE5znsESq
          MVDTVXN7QOwutvs4PxzWCy4AAbE4vjWdbg8hT6duxdXOzUz4sV9i832+niEQnE=
        - AEDx/YJkoDHhtghHoezAih5Ku7bPhvyh0zQcGT9280GVD/NHt/9qPsmwssejxDHULT24w
          5OcmsKyIJsQNaKBtnMMTkBiB5D0qPkDx3r4A3PN0cr5hHG2bMD7Nd0e0gK/j2ECYybFsU
          ODM6QAspujngkvjGrYBVYBuogUjfr/SxhqsJP+WC29pqymlDnDTR0WXQy8O2jlgjIDhGW
          lLyzucsbIpWXSUkYGOIiD1BTpV1AIAdyE0RevneX4Ad13P353ZYjnsuOYyA5jPyKgd33F
          +Su7Ni5tBZpC6cjkOAqUBiqSMqs03k0nMCHIGpaxkeoLM5HejcEyRRHCXve4L02aSzceu
          g4uYZBQWyYrTC9mC2Wk3GU7h+I4DjMZAM5yJ4LHsoNTe9sevDUqudvhcAp8dVzV0Wqcdf
          /wqI0FY0A60yf8l1/l3W+R8ngXhiDmSqKxJu7hH484rZiGocMzoZOSBgocohc6Dolmw/F
          hk4jWFqH4RUBcQ1DsuaoaSubMnoiRaTIQUEqu4cCtrpSwBlrWH2Y2ALbgUfqQ3lh1Ly4T
          TwBBA+YG12iMkfVSylueyclsPPjbrAl58vIMzqKvbmLRaLcHIeP9B8mG+erns+9IJdfd6
          eMj6wXF+ax5IZ4Q3iKLYRMBiPxEbmrCDv8pF/YxLvFAhbe58qAFNyHQXsBL650=
        - HmkOF7ANWivTBggsMCD22eDs922HDbaXOC2hQuHd2AjQ65J3cGrKoVAS54FZQEZJfo2m4
          lhrpV9tVi37oeclLQpA70ROnmcBU/6VtQbe5QTiJ2bl/U6tzxTZVETEtlI8RouTa2pIGn
          E+hjQMGChARibHYfSbkAJDNloagqEqVYxqEm2z/W8f6l9mgx3H6N+JTQKSQ2cWXWRL52f
          cjQtmM5Q6sFI3g+h+rtp33y4KkxNu2ft/r/ywvONig2lIiVFu6c5fmMtPgQC1FZhfS4a4
          J7EUnC+NSI9c4c9UekTD/+vlYkragmN5qHqKSVQ5uKBIQ0phVopx0Bz2xbGQeX2WhlGc0
          4PcQbR9sXuc2eeOnkwITkXO8UvuyDjlC3Ou+3H2OF+aLu/7vS+IveXcdYEXud35KajGr8
          089NV/gxkdgVilIvrA7SBUpOwsGwPIBbL+V5bgDs/tKaJlKHHWjHh+1NTdTOZj22mLruZ
          cw0mgNHIu1bio76dacpccVg6OJeiENhegGK/3PVOq35yGRkXiXfZXD3kWuZhQlJcr0ZA9
          WGT5y3wm5nYQnbGKvpl6xQEEVau44OpJJ7sq6NJvT+Vepciaa8zVIYBA13+V9V4ZD9HKR
          Mj5YpqNhu5busznplHly8+vml7xrYvEsAaJ8nuG59QHBfUngT/6oBK0RM0gFVM=
        - v9mJQf7JSBzqi/BdOI04pEEas3WC5b3bqbTzuOPzJMHDle45ILO1iE+VyISCuXSz5FM8i
          jsjSiTz9e/5j1s30KrSlZERvFcUILV9Hoscd/qtG5W/O011AHxZi8AstkOUWT7ouEas0S
          ugkYlmFk7oKRYk2E6mzH3zmmkrVz/19UWgT6VZ+OiatKLA0VVJPnwexVLk9eIKo0TmSDf
          Ush2p37+ViiPWm18c24g3do7aAUovWWCWaRvsIADd41VBI5yq3jHnpARNkSHoQ8cP3KBF
          EdOV/iRa2oGh9DsXYiJ/aF56KXPfbIzz7GcGjGzGYbylEB/jPfIJDWcEQpW3c4z5CfDy1
          CUt5UV5Rx+ud8aZQHns46EdQ5iXdbHuUzAABNZcF5mwlKgCXtj6cuTHmwUPOSZhI9MF8G
          fEzamzcdvJfQES6dF5m4WxipcEFcbycfO2AC2mZE/pfFyQb/+89UFvBuAbH2SYDEO4B5U
          /e6k9Vz9/x7YlcuSaxEmkT/BvDJEgoLbhDK6Cg3jAmFy73NaNPfDZpGDCYJuBhVUQoMtQ
          zTP4ubioHgr5ptlDu/4kl5rB/XvdQJhgduorwxNOEx09dMF03R2c4Jxx6j65oafUTBrXN
          MsQeJB1Oz6r3XgAgHf7cDrun+QpCmSvQX/g2HmaFe/3+VSc5OkzpvqL2EME9cE=
        - uPQObMpyXDdQEonEZQE+bPD4x1UC9jri6jnrf8G/MR61M6z04iWpcVDJyEWrCHpXtW9wf
          tG0kUqlJ5rDkVeEV3AsMoC3kGo77vypNby+rzNC9c31OmJJrJdckxn+i9R1jNp+qJBBLE
          6P9KRfxEUXy5MvazWZCiFU1SD9gVMmGmcHmqgWITg7fCuK06X9YN3sglyWc4+aXOlRQ4L
          2sVV3/Gp7sBVpfBkNC89UwgdfT83V3JBnyPXQskUepktzRG63gl/HIdJQv1PiIZIowYVB
          v+O7ONAP5qWuSj56s5NrI9mkWrggjIV8PqksdfjRs4j8iDMk811KdHESWr7Zve9oBcy5S
          QNyJuEEBh87Pi0Qs5TYZePdzix2RFkYpf0KzTejcKdxvZ3AGteMuTvUQjMJdIHBqSOQYB
          cuN1+O3KY/giljAY3J5VqYzo9haUGCNQiaxnWNOoXiY5JQA4x2gqP8j1xwUvTSiflYcJW
          LDmk3CIHtQMHnMjdHr1PCtcCqapEgmujy2K5DK1tHTtSLzUEGGmeRkVU/TGeqfxwsPJZm
          KL3fYZ8Y79bUByzg0TxCNtOag8WEylMIdaZ2T4HmODDwFhMC9jGIO/AEug05zZ6UwRwMD
          zYWR1P9/LuDMvp545QSeljfVSYsDcuYOPLB6rcjcBbFvwhXEJQ8A03cX4mWB4o=
        - j/ddmhWOMTZsSHxA2BanUiSAXp15L7Lv83HdN86GVFBFqGGHhR5vvPTvwNszzMnV8rxCw
          de1MqLKNbkcL8DnHnQQSThWQ9DPliMhMexJPzJ5PW27RNK2IzmBMsY7+puziupQz8V9n/
          7h6r/6IXgy/TfyUBYCp3+3TsYoTFVGSezcv0Ksi18CyTxg1bHeUwq9TOYbKD56p0cgkvF
          9aIOWqB3ElRvbDa21bLbF9IGnJv8oRgDDW1CTQKKeE8JcGQGAu2SBscrJwCJbuPsNeuIG
          oPkpZxIV7f0eN6WQJyy+nDvpsYnCiKgKdwhPodNVllt7kkCUkpnYiL/RG3SN0em+HyPkc
          p9PZ2fXay6CSVRWJYqs60LS/Oyi9Krno6sexmjtxx208R4RpBv6B9cKUIAAX1HzoEqIa8
          +ZFR6NhaTXtWo308foAizMTpVxk5fovI7x3I7su1Jfkx9bk78BIX07fB4G+onS8An48CP
          HEHhiwsgzg4CkmKQCann3MOAz/b4GK3BeCnh8v65wv9mAp/XJOqSUaZ3vSbhj1VIGqXRv
          l3ruvfaeKBSBDxhmDduc7W3IetR62ytX1lQXkiL+HO6B8NDkhq/oJObnZDj9YnAh0jxsu
          niJz9cyUz36bqs9dyATb6aOqg1p4uRo05HdopLBfGIX6+3GHqeVwTj+kjWm+1U=
