# List of packages to be included/installed in ISO
# If these have dependencies, they will be pulled in automatically
#

# cgts-mtce-common
cgts-mtce-common
cgts-mtce-common-pmon
cgts-mtce-common-rmon
cgts-mtce-common-hwmon
cgts-mtce-common-guestAgent
cgts-mtce-common-guestServer
cgts-mtce-common-hostw

# cgts-mtce-compute
cgts-mtce-compute

# cgts-mtce-control
cgts-mtce-control

# cgts-mtce-storage
cgts-mtce-storage

# pxe-network-installer
pxe-network-installer

# platform-kickstarts
platform-kickstarts
