#!/bin/bash
#
# Copyright (c) 2013-2018 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

# update inventory MOTD if motd.system content present

[ -f /etc/inventory/motd.system ] && cat /etc/inventory/motd.system || true
